### ISSUE TITLE
Can I repersent an array of domain vars?

### ISSUE THREAD

**Issue by arichiardi** [aengelberg/loco#7]
Hi! I am a Constraint Programming newbie, taking Discrete Optimization course on Coursera.
I am tryng to implement a simple model:
    c4 c3 c2 c1
      S  E  N  D +
      M  O  R  E =
    ----------------
   M  O  N  E  Y

but I am stuck with:

    [($in :letters (map int [\s \e \n \d \m \o \r \y]))
       ($in :n 0 9)
       ($in :cv 0 1)
       ($in :values [:n :n :n :n :n :n :n :n (???)])
       ($in :carries [:cv :cv :cv :cv (???)])
    ])

Is there a way to declare a vector of ```:letters``` ? Or am I doing something completely wrong and loco actually uses a different approach to the problem?

**Comment by aengelberg** [comment]
Hello Andrea,

Great to hear you are taking Discrete Optimization. It is that exact course that inspired me to get into CP and write this library.

Currently there is no specific shortcut or syntactic sugar to specify multiple constraints at once.

However, given the functional / flexible nature of Clojure, it's easy to generate such constraints with list comprehensions. Also, keep in mind that vectors beginning with keywords are fair game for variable names (specified [here](https://github.com/aengelberg/loco#names) in the readme). For instance, `[:n 0]` up to `[:n 9]`, or `[:l \s]` up to `[:l \y]`.

    (concat (for [i (range 0 9)]
              ($in [:n i] 0 9))
            (for [letter "sendmory"]
              ($in [:l letter] 0 9))
            ...)

Actually, for the letters it might make more sense to have separate keywords, `:S` `:E` etc. It's up to you.

Good luck!
--Alex

**Comment by arichiardi** [comment]
Ahah wow that course is great :D 
If I can ask, what didn't you like about core.logic? I am actually planning to use both, as exercise and exploration of which one can be the best fit. Would it be possible to add the aforementioned approach and add some sugar? I could take care of it, but I don't know if it make sense for Choco...

**Comment by aengelberg** [comment]
[This](https://github.com/aengelberg/loco#about-loco) section in the README mentions the origin / motivation of loco and how it differs from core.logic.

In fact, Choco does have support for creating arrays or matrices of variables. However, I believe that functionality is not necessary in Clojure because the user has just as much power to create batches of constraints. As you can see from my example above, it only takes a few additional characters to initiate a for-loop to generate the full collection of constraints.

I will close this issue for now, but feel free to re-open it if you have further questions or comments.

Thanks for trying out loco!
--Alex

**Comment by Engelberg** [comment]
As an early beta tester of Loco, I'm in agreement with Alex's comment that since Loco allows you to "subscript" variables by means of a vector (e.g., [:a 1] is conceptually like <a href="http://www.codecogs.com/eqnedit.php?latex=a_1" target="_blank"><img src="http://latex.codecogs.com/gif.latex?a_1" title="a_1" /></a>), and you can easily provide constraints for a whole bunch of variables at once with for comprehensions in Clojure, there's little need for a specialized array syntax.  (If you did want to add such a syntax, though, you don't really need specialized support from Choco, it can just be handled as an expansion to Loco's way of representing constraints).

I wrote some blog posts demonstrating the application of Loco to a variety of common constraint problems.  Reading them might give you more of an idea of how to use them.

http://programming-puzzler.blogspot.com/2014/03/optimization-with-loco.html

http://programming-puzzler.blogspot.com/2014/03/appointment-scheduling-in-clojure-with.html

http://programming-puzzler.blogspot.com/2014/03/sudoku-in-loco.html

**Comment by arichiardi** [comment]
OK understood, thank you for the blog posts, it will ben a pleasure to read and learn from them. Maybe I can just improve the "examples" section :)
